collection_name: agent
persist_directory: backend/database/chroma
k: 3
data_path: backend/data/knowledge
md5_hex_store: backend/database/chroma/md5.text
allow_knowledge_file_type: ["txt", "pdf"]

chunk_size: 200
chunk_overlap: 20
separators: ["\n\n", "\n", ".", "!", "?", "。", "！", "？", " ", ""]
